/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LeaseStatus = IDL.Variant({
  'active' : IDL.Null,
  'archived' : IDL.Null,
});
export const LeaseListing = IDL.Record({
  'id' : IDL.Text,
  'status' : LeaseStatus,
  'owner' : IDL.Principal,
  'area' : IDL.Nat,
  'capacity' : IDL.Nat,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const LeaseRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  }),
  'listingId' : IDL.Text,
  'info' : IDL.Text,
  'tenant' : IDL.Principal,
  'requestDate' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'archiveLeaseListing' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createLeaseListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'getActiveListings' : IDL.Func([], [IDL.Vec(LeaseListing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOwnerListings' : IDL.Func([], [IDL.Vec(LeaseListing)], ['query']),
  'getRequestsForListing' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LeaseRequest)],
      ['query'],
    ),
  'getRequestsForOwner' : IDL.Func([], [IDL.Vec(LeaseRequest)], ['query']),
  'getTenantRequests' : IDL.Func([], [IDL.Vec(LeaseRequest)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitLeaseRequest' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'updateLeaseListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateRequestStatus' : IDL.Func(
      [IDL.Text, IDL.Variant({ 'rejected' : IDL.Null, 'accepted' : IDL.Null })],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LeaseStatus = IDL.Variant({
    'active' : IDL.Null,
    'archived' : IDL.Null,
  });
  const LeaseListing = IDL.Record({
    'id' : IDL.Text,
    'status' : LeaseStatus,
    'owner' : IDL.Principal,
    'area' : IDL.Nat,
    'capacity' : IDL.Nat,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const LeaseRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'cancelled' : IDL.Null,
      'pending' : IDL.Null,
      'rejected' : IDL.Null,
      'accepted' : IDL.Null,
    }),
    'listingId' : IDL.Text,
    'info' : IDL.Text,
    'tenant' : IDL.Principal,
    'requestDate' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'archiveLeaseListing' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createLeaseListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'getActiveListings' : IDL.Func([], [IDL.Vec(LeaseListing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOwnerListings' : IDL.Func([], [IDL.Vec(LeaseListing)], ['query']),
    'getRequestsForListing' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LeaseRequest)],
        ['query'],
      ),
    'getRequestsForOwner' : IDL.Func([], [IDL.Vec(LeaseRequest)], ['query']),
    'getTenantRequests' : IDL.Func([], [IDL.Vec(LeaseRequest)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitLeaseRequest' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'updateLeaseListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateRequestStatus' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({ 'rejected' : IDL.Null, 'accepted' : IDL.Null }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };