/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LeaseListing {
  'id' : string,
  'status' : LeaseStatus,
  'owner' : Principal,
  'area' : [] | [bigint],
  'code' : string,
  'splitRatio' : SplitRatio,
  'capacity' : [] | [bigint],
  'location' : [] | [string],
}
export interface LeaseRequest {
  'id' : string,
  'status' : { 'cancelled' : null } |
    { 'pending' : null } |
    { 'rejected' : null } |
    { 'accepted' : null },
  'listingId' : string,
  'info' : string,
  'tenant' : Principal,
  'requestDate' : Time,
}
export type LeaseStatus = { 'active' : null } |
  { 'archived' : null };
export interface SplitRatio { 'nlo' : bigint, 'ulo' : bigint }
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'archiveLeaseListing' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createLeaseListing' : ActorMethod<
    [string, string, SplitRatio, [] | [string], [] | [bigint], [] | [bigint]],
    string
  >,
  'getActiveListings' : ActorMethod<[], Array<LeaseListing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOwnerListings' : ActorMethod<[], Array<LeaseListing>>,
  'getRequestsForListing' : ActorMethod<[string], Array<LeaseRequest>>,
  'getRequestsForOwner' : ActorMethod<[], Array<LeaseRequest>>,
  'getTenantRequests' : ActorMethod<[], Array<LeaseRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitLeaseRequest' : ActorMethod<[string, string], string>,
  'updateLeaseListing' : ActorMethod<
    [string, string, SplitRatio, [] | [string], [] | [bigint], [] | [bigint]],
    undefined
  >,
  'updateRequestStatus' : ActorMethod<
    [string, { 'rejected' : null } | { 'accepted' : null }],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];