/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SplitRatio {
    nlo: bigint;
    ulo: bigint;
}
export interface LeaseRequest {
    id: string;
    status: Variant_cancelled_pending_rejected_accepted;
    listingId: string;
    info: string;
    tenant: Principal;
    requestDate: Time;
}
export type Time = bigint;
export interface UserProfile {
    name: string;
}
export interface LeaseListing {
    id: string;
    status: LeaseStatus;
    owner: Principal;
    area?: bigint;
    code: string;
    splitRatio: SplitRatio;
    capacity?: bigint;
    location?: string;
}
export enum LeaseStatus {
    active = "active",
    archived = "archived"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_cancelled_pending_rejected_accepted {
    cancelled = "cancelled",
    pending = "pending",
    rejected = "rejected",
    accepted = "accepted"
}
export enum Variant_rejected_accepted {
    rejected = "rejected",
    accepted = "accepted"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    archiveLeaseListing(id: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createLeaseListing(id: string, code: string, splitRatio: SplitRatio, location: string | null, area: bigint | null, capacity: bigint | null): Promise<string>;
    getActiveListings(): Promise<Array<LeaseListing>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getOwnerListings(): Promise<Array<LeaseListing>>;
    getRequestsForListing(listingId: string): Promise<Array<LeaseRequest>>;
    getRequestsForOwner(): Promise<Array<LeaseRequest>>;
    getTenantRequests(): Promise<Array<LeaseRequest>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitLeaseRequest(listingId: string, info: string): Promise<string>;
    updateLeaseListing(id: string, code: string, splitRatio: SplitRatio, location: string | null, area: bigint | null, capacity: bigint | null): Promise<void>;
    updateRequestStatus(requestId: string, newStatus: Variant_rejected_accepted): Promise<void>;
}
import type { LeaseListing as _LeaseListing, LeaseRequest as _LeaseRequest, LeaseStatus as _LeaseStatus, SplitRatio as _SplitRatio, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async archiveLeaseListing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveLeaseListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveLeaseListing(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createLeaseListing(arg0: string, arg1: string, arg2: SplitRatio, arg3: string | null, arg4: bigint | null, arg5: bigint | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createLeaseListing(arg0, arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLeaseListing(arg0, arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async getActiveListings(): Promise<Array<LeaseListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveListings();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveListings();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnerListings(): Promise<Array<LeaseListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnerListings();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnerListings();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRequestsForListing(arg0: string): Promise<Array<LeaseRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRequestsForListing(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRequestsForListing(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRequestsForOwner(): Promise<Array<LeaseRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRequestsForOwner();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRequestsForOwner();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTenantRequests(): Promise<Array<LeaseRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTenantRequests();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTenantRequests();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitLeaseRequest(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLeaseRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLeaseRequest(arg0, arg1);
            return result;
        }
    }
    async updateLeaseListing(arg0: string, arg1: string, arg2: SplitRatio, arg3: string | null, arg4: bigint | null, arg5: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeaseListing(arg0, arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeaseListing(arg0, arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateRequestStatus(arg0: string, arg1: Variant_rejected_accepted): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRequestStatus(arg0, to_candid_variant_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRequestStatus(arg0, to_candid_variant_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_LeaseListing_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaseListing): LeaseListing {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_LeaseRequest_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaseRequest): LeaseRequest {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_LeaseStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaseStatus): LeaseStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        cancelled: null;
    } | {
        pending: null;
    } | {
        rejected: null;
    } | {
        accepted: null;
    };
    listingId: string;
    info: string;
    tenant: Principal;
    requestDate: _Time;
}): {
    id: string;
    status: Variant_cancelled_pending_rejected_accepted;
    listingId: string;
    info: string;
    tenant: Principal;
    requestDate: Time;
} {
    return {
        id: value.id,
        status: from_candid_variant_n18(_uploadFile, _downloadFile, value.status),
        listingId: value.listingId,
        info: value.info,
        tenant: value.tenant,
        requestDate: value.requestDate
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _LeaseStatus;
    owner: Principal;
    area: [] | [bigint];
    code: string;
    splitRatio: _SplitRatio;
    capacity: [] | [bigint];
    location: [] | [string];
}): {
    id: string;
    status: LeaseStatus;
    owner: Principal;
    area?: bigint;
    code: string;
    splitRatio: SplitRatio;
    capacity?: bigint;
    location?: string;
} {
    return {
        id: value.id,
        status: from_candid_LeaseStatus_n8(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        area: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.area)),
        code: value.code,
        splitRatio: value.splitRatio,
        capacity: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.capacity)),
        location: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): Variant_cancelled_pending_rejected_accepted {
    return "cancelled" in value ? Variant_cancelled_pending_rejected_accepted.cancelled : "pending" in value ? Variant_cancelled_pending_rejected_accepted.pending : "rejected" in value ? Variant_cancelled_pending_rejected_accepted.rejected : "accepted" in value ? Variant_cancelled_pending_rejected_accepted.accepted : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    archived: null;
}): LeaseStatus {
    return "active" in value ? LeaseStatus.active : "archived" in value ? LeaseStatus.archived : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaseRequest>): Array<LeaseRequest> {
    return value.map((x)=>from_candid_LeaseRequest_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaseListing>): Array<LeaseListing> {
    return value.map((x)=>from_candid_LeaseListing_n6(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_rejected_accepted): {
    rejected: null;
} | {
    accepted: null;
} {
    return value == Variant_rejected_accepted.rejected ? {
        rejected: null
    } : value == Variant_rejected_accepted.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
